rm artificiallang_correlations
python3 diststruct_experiments.py artificiallanguages/language1 artificiallangfeatures.txt >>artificiallang_correlations
python3 diststruct_experiments.py artificiallanguages/language2 artificiallangfeatures.txt >>artificiallang_correlations
python3 diststruct_experiments.py artificiallanguages/language3 artificiallangfeatures.txt >>artificiallang_correlations
python3 diststruct_experiments.py artificiallanguages/language4 artificiallangfeatures.txt >>artificiallang_correlations
python3 diststruct_experiments.py artificiallanguages/language5 artificiallangfeatures.txt >>artificiallang_correlations
python3 diststruct_experiments.py artificiallanguages/language6 artificiallangfeatures.txt >>artificiallang_correlations
python3 diststruct_experiments.py artificiallanguages/language7 artificiallangfeatures.txt >>artificiallang_correlations
python3 diststruct_experiments.py artificiallanguages/language8 artificiallangfeatures.txt >>artificiallang_correlations
python3 diststruct_experiments.py artificiallanguages/language9 artificiallangfeatures.txt >>artificiallang_correlations
python3 diststruct_experiments.py artificiallanguages/language10 artificiallangfeatures.txt >>artificiallang_correlations
python3 diststruct_experiments.py artificiallanguages/language11 artificiallangfeatures.txt >>artificiallang_correlations
python3 diststruct_experiments.py artificiallanguages/language12 artificiallangfeatures.txt >>artificiallang_correlations
