python3 diststruct_experiments.py artificiallanguages/language1
mv phone-dendrogram.pdf ../../../sigmorphon2019/lang1-phone-dendrogram.pdf
python3 diststruct_experiments.py artificiallanguages/language2
mv phone-dendrogram.pdf ../../../sigmorphon2019/lang2-phone-dendrogram.pdf
python3 diststruct_experiments.py artificiallanguages/language3
mv phone-dendrogram.pdf ../../../sigmorphon2019/lang3-phone-dendrogram.pdf
python3 diststruct_experiments.py artificiallanguages/language4
mv phone-dendrogram.pdf ../../../sigmorphon2019/lang4-phone-dendrogram.pdf
python3 diststruct_experiments.py artificiallanguages/language5
mv phone-dendrogram.pdf ../../../sigmorphon2019/lang5-phone-dendrogram.pdf
python3 diststruct_experiments.py artificiallanguages/language6
mv phone-dendrogram.pdf ../../../sigmorphon2019/lang6-phone-dendrogram.pdf
python3 diststruct_experiments.py artificiallanguages/language7
mv phone-dendrogram.pdf ../../../sigmorphon2019/lang7-phone-dendrogram.pdf
python3 diststruct_experiments.py artificiallanguages/language8
mv phone-dendrogram.pdf ../../../sigmorphon2019/lang8-phone-dendrogram.pdf
python3 diststruct_experiments.py artificiallanguages/language9
mv phone-dendrogram.pdf ../../../sigmorphon2019/lang9-phone-dendrogram.pdf
python3 diststruct_experiments.py artificiallanguages/language10
mv phone-dendrogram.pdf ../../../sigmorphon2019/lang10-phone-dendrogram.pdf
python3 diststruct_experiments.py artificiallanguages/language11
mv phone-dendrogram.pdf ../../../sigmorphon2019/lang11-phone-dendrogram.pdf
python3 diststruct_experiments.py artificiallanguages/language12
mv phone-dendrogram.pdf ../../../sigmorphon2019/lang12-phone-dendrogram.pdf
